import Head from 'next/head';
import Image from 'next/image';
import { buildUrl } from 'cloudinary-build-url';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

export default function Home() {
  // const url = buildUrl('cld-sample-2', {
  //   cloud: {
  //     cloudName: 'dczqq7vyb',
  //   },
  //   transformations: {
  //     effect: {
  //       name: 'pixelate',
  //       value: 40,
  //     },
  //   },
  // });
  const url = 'https://res.cloudinary.com/dczqq7vyb/image/upload/v1660755506/cld-sample-2.jpg';

  const urlBlurred = buildUrl('cld-sample-2', {
    cloud: {
      cloudName: 'dczqq7vyb',
    },
    transformations: {
      effect: 'blur:1000',
      quality: 1,
    },
  });

  const [image, setImage] = useState();

  useEffect(() => {
    setTimeout(() => {
      setImage(url);
    }, 2000);
  }, [url]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <Image src="/galaxy.jpeg" alt="Galaxy" width={1000} height={750} />
          <h3>Local Image</h3>
        </div>

        <div className={styles.card}>
          <Image
            src="https://res.cloudinary.com/dczqq7vyb/image/upload/v1660755506/cld-sample-2.jpg"
            alt="Galaxy"
            width={1000}
            height={750}
          />
          <h3>Cloudinary Image</h3>
        </div>

        {/* <div className={styles.card}>
          <Image src={url} alt="Mountain" width={1000} height={750} />
          <h3>Cloudinary - Pixelated Placeholder</h3>
        </div> */}

        <div className={styles.card}>
          <div
            style={{
              position: 'relative',
              height: 0,
              paddingTop: `${(750 / 1000) * 100}%`,
              backgroundImage: `url(${urlBlurred})`,
              backgroundPosition: 'center center',
              backgroundSize: `100%`,
            }}
          >
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
              }}
            >
              {image && (
                <Image src={image} alt="Galaxy" width={1000} height={750} />
              )}
            </div>
          </div>
          <h3>Cloudinary - Blurred Placeholder</h3>
        </div>
      </main>

      <footer className={styles.footer}>RSEBEX</footer>
    </div>
  );
}
